version: '3'
services:
  nginx: 
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    ports:
      - '80:80'
      - '281:81'
      - '443:443'
    volumes:
      - /docker/nginx/data:/data
      - /docker/nginx/letsencrypt:/etc/letsencrypt
      - /docker/nginx/snippets:/snippets:ro
    networks:
      - proxy
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - "/docker/authelia:/config"
    networks:
      - proxy
    tty: true
    stdin_open: true
    ports:
      - "9091:9091"
    restart: unless-stopped
    healthcheck:
      ## In production the healthcheck section should be commented.
      disable: true
    environment:
      - TZ=Europe/London
    depends_on:
      - "nginx"
networks:
  proxy:
    external: true 
