version: "3"
networks:
  loki:
services:
  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
      - /docker/promtail:/etc/promtail
      - /docker/nginx:/docker/nginx:ro
    ports:
      - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
